library(openxlsx)
csdat_raw <- read.xlsx("file", sheet = "csdata")
str(csdat_raw)
head(csdat_raw)
summary(csdat_raw)
library(ggplot2)
ggplot(csdat_raw, aes(as.factor(dependents), income)) + 
   geom_boxplot() + xlab("Dependents") + ggtitle("Boxplot Income Berdasarkan Dependents")
index1 <- which(csdat_raw$riskrating == 1)
index2 <- which(csdat_raw$riskrating == 2)
index3 <- which(csdat_raw$riskrating == 3)
index4 <- which(csdat_raw$riskrating == 4)
index5 <- which(csdat_raw$riskrating == 5)
ntrain1 <- round(0.8 * length(index1))
ntrain2 <- round(0.8 * length(index2))
ntrain3 <- round(0.8 * length(index3))
ntrain4 <- round(0.8 * length(index4))
ntrain5 <- round(0.8 * length(index5))
set.seed(100)
train1_index <- sample(index1, ntrain1)
train2_index <- sample(index2, ntrain2)
train3_index <- sample(index3, ntrain3)
train4_index <- sample(index4, ntrain4)
train5_index <- sample(index5, ntrain5)
test1_index <- setdiff(index1, train1_index)
test2_index <- setdiff(index2, train2_index)
test3_index <- setdiff(index3, train3_index)
test4_index <- setdiff(index4, train4_index)
test5_index <- setdiff(index5, train5_index)
csdattrain <- do.call("rbind", list(csdat_raw[train1_index,],
   csdat_raw[train2_index,], csdat_raw[train3_index,],
   csdat_raw[train4_index,], csdat_raw[train5_index,]))
cstrain <- subset(csdattrain, select = 
   -c(contractcode,riskrating))
csdattest <- do.call("rbind", list(csdat_raw[test1_index,], csdat_raw[test2_index,], csdat_raw[test3_index,], csdat_raw[test4_index,], csdat_raw[test5_index,]))
cstest <- subset(csdattest, select = -riskrating)
cor(cstrain)
pr.out <- prcomp(cstrain, scale = TRUE, center = TRUE)
pr.out
summary(pr.out)
screeplot(pr.out, type = "line", ylim = c(0,2))
abline(h = 1, lty = 3, col = "red") menggunakan fungsi biplot()
#[16]
biplot(pr.out, scale = 0)
